platform :ios, '15.0'

target 'Redi' do
  use_frameworks!
  
  # WebRTC for direct connection to OpenAI Realtime API
  # Benefits: Built-in echo cancellation, lower latency, better audio
  pod 'GoogleWebRTC', '~> 1.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      # Required for WebRTC
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
