name: Redi
options:
  bundleIdPrefix: com.personalizedoutput
  deploymentTarget:
    iOS: "15.0"

targets:
  Redi:
    type: application
    platform: iOS
    sources:
      - App
      - Models
      - Views
      - ViewModels
      - Services
      - Assets.xcassets
      - path: StoreKitConfiguration.storekit
        buildPhase: none
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.personalizedoutput.Redi
      INFOPLIST_FILE: Info.plist
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      SWIFT_VERSION: "5.9"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""

schemes:
  Redi:
    build:
      targets:
        Redi: all
    run:
      storeKitConfiguration: StoreKitConfiguration.storekit
