#!/bin/bash

# Run this at the start of any Claude Code session working on Redi
# It outputs critical context that prevents architectural bugs

echo ""
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                    REDI ARCHITECTURE CONTEXT                          ║"
echo "╠══════════════════════════════════════════════════════════════════════╣"
echo "║                                                                       ║"
echo "║  THE 6 RULES (Learned from production bugs - January 2026):           ║"
echo "║                                                                       ║"
echo "║  1. Every Map<sessionId, X> needs cleanup in handleSessionEnd()      ║"
echo "║  2. State changes must propagate to ALL stores                        ║"
echo "║  3. isSpeaking must sync: DecisionContext AND PipelineState          ║"
echo "║  4. Mode changes must reset rule engine state                         ║"
echo "║  5. Bridge data at system boundaries (transcript → perception)       ║"
echo "║  6. Never use global scope for session state                          ║"
echo "║                                                                       ║"
echo "╠══════════════════════════════════════════════════════════════════════╣"
echo "║                                                                       ║"
echo "║  STATE STORES (All must stay in sync):                                ║"
echo "║  - DecisionContext (decisionEngine.ts)                                ║"
echo "║  - OrchestratorState (militaryGradeOrchestrator.ts)                  ║"
echo "║  - PipelineState (responsePipeline.ts)                                ║"
echo "║  - SessionManager (sessionManager.ts)                                 ║"
echo "║  - RuleEngineState (ruleEngine.ts)                                    ║"
echo "║                                                                       ║"
echo "╠══════════════════════════════════════════════════════════════════════╣"
echo "║                                                                       ║"
echo "║  KEY FILES:                                                           ║"
echo "║  - src/websocket/rediSocket.ts (routing, bridges, cleanup)           ║"
echo "║  - src/lib/redi/militaryGradeOrchestrator.ts (main pipeline)         ║"
echo "║  - src/lib/redi/haikuTriage.ts (fast responses)                      ║"
echo "║                                                                       ║"
echo "║  FOR FULL CONTEXT: Read REDI_ARCHITECTURE.md                          ║"
echo "║                                                                       ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
